name: Oppgave 16
on:
  push:
  workflow_dispatch:  

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.Naeem_Action_Workflows }}
          enable-AzPSSession: true

      - name: Run Blackjack script file
        run: ./src/oppgave_10.ps1
